// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0v0NDE_B4LxlqsHZvEFankatN74pee_8',
    appId: '1:768288377321:web:90f93813edeeec7d182378',
    messagingSenderId: '768288377321',
    projectId: 'ititraning-1f88e',
    authDomain: 'ititraning-1f88e.firebaseapp.com',
    storageBucket: 'ititraning-1f88e.appspot.com',
    measurementId: 'G-CV83HNG2WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcSisaZhTZLqiLT1iHTfbW78R-FJ-Wbec',
    appId: '1:768288377321:android:ab2b6093e1bdbbfe182378',
    messagingSenderId: '768288377321',
    projectId: 'ititraning-1f88e',
    storageBucket: 'ititraning-1f88e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmBTlXemkBQd-HcFITZuoEckhJDfwdX80',
    appId: '1:768288377321:ios:e7e08d869a602c2c182378',
    messagingSenderId: '768288377321',
    projectId: 'ititraning-1f88e',
    storageBucket: 'ititraning-1f88e.appspot.com',
    iosClientId: '768288377321-u5mrt7hn3shbbhc59urkbbe0kju1uqku.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
